name: Codequality
on:
  - push
jobs:
  harden_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@aadec899646c8e0f34c52d9219c2faac36626b55
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@ba37328d4ea95eaf8b3bd6c6cef308f709a5f2ec
  test:
    needs: harden_actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@aadec899646c8e0f34c52d9219c2faac36626b55
        with:
          ref: ${{ github.ref_name || github.base_ref }}
      - name: Add Varnish repo
        run: |
          tee /etc/apt/sources.list.d/varnishcache_varnish70.list > /dev/null <<-EOF
            deb https://packagecloud.io/varnishcache/varnish70/ubuntu/ focal main
            deb-src https://packagecloud.io/varnishcache/varnish70/ubuntu/ focal main
          EOF
          apt-update -y
      - name: Install Varnish
        uses: awalsh128/cache-apt-pkgs-action@2555a377dfb0ca4763693499998da808e8d5afa0
        with:
          packages: varnish
      - name: Install PHP
        uses: shivammathur/setup-php@6d7209f44a25a59e904b1ee9f3b0c33ab2cd888d
        with:
          php-version: '8.2'
          extensions: pdo
      - name: Install MySQL
        uses: shogo82148/actions-setup-mysql@e67c00aa3a23825c685b5d978336f29a78d7a532
        with:
          mysql-version: '8.0'
      - name: Create DB
        run: mysql -uroot -e 'Create database wordpress'
      - name: Install Wordpress
        run: |
              wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
              chmod +x ./wp-cli.phar
              ./wp-cli.phar core download --path=. --locale=en_US
              ./wp-cli.phar config create --dbhost='127.0.0.1' --dbname='wordpress' --dbuser='root' --dbpass=''
              ./wp-cli.phar config set WP_HOME 'http://localhost:8000'
              ./wp-cli.phar config set WP_SITEURL 'http://localhost:8000'
              ./wp-cli.phar core install --url='http://localhost:8000' --title='Varnish Cache' --admin_user='admin' --admin_password='admin' --admin_email='info@admin.fake'
              ./wp-cli.phar rewrite structure '/%postname%/'
      - name: Start PHP webserver
        run:  nohup php -S localhost:8000 &
      - name: check dir
        run: ls
      - name: Test Curl
        run: curl -i localhost:8000
      
